### ISSUE TITLE
First argument must be a string or Buffer

### ISSUE THREAD

**Issue by azachar** [mollie/mollie-api-node#21]
Hi there, 
I am having an issue with the latest version ``1.3.2``

```js
TypeError: First argument must be a string or Buffer
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:443:11)
    at Client.module.exports.Client.callRest (/home/ubuntu/vividoctor/node_modules/mollie-api-node/lib/mollie/api/client.js:109:15)
    at Mandates.module.exports.Base.all (/home/ubuntu/vividoctor/node_modules/mollie-api-node/lib/mollie/api/resource/base.js:111:23)
```

while calling

```js
mollie.customers_mandates.withParentId('cst_XXXXX').all(function (mandates) {
  **throws error**
});
```

When I switched back to ``1.3.1.`` it just works fine.

Thanks for your fix.

Best regards,
Andrej

**Comment by Thijs-Riezebeek** [comment]
Hi azachar,

Thank you for opening this issue! This is indeed a bug in our client and it has been fixed in version 1.3.3. Which I have just released.

Kind regards,
Thijs Riezebeek
