### ISSUE TITLE
Error when trying to get payments for an order

### ISSUE THREAD

**Issue by martijnvdbrug** [mollie/mollie-api-node#391]
Hi! I am one of the maintainers of the Vendure Mollie integration, and we use the Mollie Node client. After upgrading to V4 I can not seem to get payments of an order anymore, it results in `#<Object> is not a constructor`.

Run this script to reproduce:

```js
// repro.js

import { createMollieClient } from "@mollie/api-client"; // Both v4.1.0 and 4.0.0 have this issue, 3.7.0 works

const apiKey = "test_xxxx";
const orderId = "ord_1.acekxu"; // An order with status Paid

(async () => {
    const mollieClient = createMollieClient({ apiKey });
    const mollieOrder = await mollieClient.orders.get(orderId);
    const molliePayments = await mollieOrder.getPayments(); // This throws the error
    console.log(molliePayments);
})();

```

**Comment by janpaepke** [comment]
Thank you @martijnvdbrug for flagging this issue.
Before I get into the bug analysis I'd like to make you aware that orders are being deprecated in favour of payments.
This is likely relevant for your long term plans in your integration.
From the mollie docs:
>**Our Orders API will be replaced with a full-featured Payments API**
>
>We no longer recommend implementing the Orders API. Please refer to the Payments API instead. We are actively working on adding support for Klarna, Billie, in3 and Vouchers to the Payments API later this year


## Issue analysis

After investigating this issue using your example, I can confirm this bug.

Error Details:
```
TypeError: #<Object> is not a constructor
    at Object.resolve (<anonymous>)
    at Object.<anonymous> ([localpath]/mollie-api-node/node_modules/ruply/compiled/cjs/ruply.min.js:1:577)
    at Object.runIf ([localpath]/mollie-api-node/node_modules/ruply/compiled/cjs/ruply.min.js:1:369)
    at OrderHelper.getPayments ([localpath]/mollie-api-node/dist/mollie.cjs.js:2410:28)
    at file://[localpath]/repro.mjs:42:43
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

It seems this started with the introduction of [ruply](https://github.com/Pimm/ruply), a library maintained by @Pimm.
[Prior to v4.0.0](https://github.com/mollie/mollie-api-node/commit/07ce39a90d5186b8d7615aeaeae0245ea381ee83#diff-e451ee7c55eba6aceeb7f34a9b4787d4d9d4b4353f7fb0727a93146f419c2497) getPayments method used 'resolveIf', which used to have [a simpler nullish-comparison implementation](https://github.com/mollie/mollie-api-node/blob/v3.7.0/src/plumbing/resolveIf.ts).

The actual issue though comes from this line:
```
runIf(this.embedded?.payments, Promise.resolve)
```

I believe this leaves the resolve function unbound, which causes the issue.
I have tested this new version and it does indeed fix the error and returns the payments as expected:
```
runIf(this.embedded?.payments, Promise.resolve.bind(Promise))
```
Since `resolveIf` is still in use (but now using `runIf`) for Chargebacks, Captures and Refunds, it is likely this bug also concerns  these instances.

**My suggested solution would be to update the resolveIf function to use a bound version of `Promise.resolve` (as it currently doesn't). And use it for order.getPayments() as well.**

@Pimm , if you concur, we can add this to the next release.
Additionally you might want to consider improving logging output in *ruply* for this specific scenario, as this is quite likely to happen to other consumers as well.
